// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWv5nVMiy_S7bBDm5qMbLHYoVbWL0kU4',
    appId: '1:736888497416:web:a229989fba96dde08d78bd',
    messagingSenderId: '736888497416',
    projectId: 'vision-companion-ba039',
    authDomain: 'vision-companion-ba039.firebaseapp.com',
    storageBucket: 'vision-companion-ba039.firebasestorage.app',
    measurementId: 'G-8D96MD2S8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5bBaqxjT6zWYK8G3CcATCMTcIj7u8lg',
    appId: '1:736888497416:android:462b6ec4a9db171b8d78bd',
    messagingSenderId: '736888497416',
    projectId: 'vision-companion-ba039',
    storageBucket: 'vision-companion-ba039.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4YMnh3tqqxmbiQpqFAlWGf2LR8yzKWuQ',
    appId: '1:736888497416:ios:32d802d2544fbf988d78bd',
    messagingSenderId: '736888497416',
    projectId: 'vision-companion-ba039',
    storageBucket: 'vision-companion-ba039.firebasestorage.app',
    iosClientId: '736888497416-ot3e5l1ifc5qrikiv45rkq4jt09vc8oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionCompanion',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4YMnh3tqqxmbiQpqFAlWGf2LR8yzKWuQ',
    appId: '1:736888497416:ios:32d802d2544fbf988d78bd',
    messagingSenderId: '736888497416',
    projectId: 'vision-companion-ba039',
    storageBucket: 'vision-companion-ba039.firebasestorage.app',
    iosClientId: '736888497416-ot3e5l1ifc5qrikiv45rkq4jt09vc8oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionCompanion',
  );
}
